[package]
name = "dl-srt-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.161"
thiserror = "2.0.3"
tracing = { version = "0.1.40", optional = true }

[build-dependencies]
bindgen = "0.70.1"

[features]
tracing = ["dep:tracing"]

[dev-dependencies]
serial_test = "3.2.0"
